%%This script processes a CNMF *.mat file generated by the
%%CNMFEBatchProcessor script.  Each time the script is run, you will be
%%prompted to select a *.mat file.  The results will be automatcially
%%saved as a *.mat file with the CNMFsorted filename.  The full workspace
%%will be saved with the CNMF filename.
%%James Hyde 1/17/18


%% get the file name and paths for each folder to be processed

[FileName, PathName] = uigetfile({'*.mat'}, 'File Selector')

cd(PathName);
load(FileName);
% ----------------------  WITH MANUAL INTERVENTION  --------------------  %

with_manual_intervention = true;

%%
Coor = neuron.show_contours(0.6);

%% add a manual intervention and run the whole procedure for a second time


neuron.options.spatial_algorithm = 'nnls';
if with_manual_intervention
    show_merge = true; 
    neuron.orderROIs('snr');   % order neurons in different ways {'snr', 'decay_time', 'mean', 'circularity'}
    neuron.viewNeurons_x([], neuron.C_raw);
    
%     merge closeby neurons
    neuron.merge_close_neighbors(true, dmin_only);
    
    % delete neurons
    tags = neuron.tag_neurons_parallel();  % find neurons with fewer nonzero pixels than min_pixel and silent calcium transients
    ids = find(tags>0); 
    if ~isempty(ids)
        neuron.viewNeurons_x(ids, neuron.C_raw);
    end
end

%% show neuron contours
Coor = neuron.show_contours(0.6);

%% Save the Workspace
name = strcat((FileName{k}(1:end-4)),'CNMF', 'sorted','.mat');
save(name, '-v7.3');

name = strcat((FileName{k}(1:end-4)),'CNMF', '_final', '.mat');
save(name, 'Coor', 'neuron', 'PNR', 'name', 'center', 'Cn',   '-v7.3');

clear
