%Step 1: pythonToMatlabConversion.m
%Step 2: extractEventRelatedCaTraces.m
%Step 3: plotAvgEventRelatedTraces.m

close all;

numPlanes = 2; %SET THIS VALUE TO THE NUMBER OF PLANES RECORDED FROM
licks = 2; %set to 2 to skip licking events, otherwise set to 1
trialsToAnalyze = ':'; %list trial numbers in brackets, or write ':' to analyze all
odor = 0; %0 if no olfactometer, set to 1 for odor trials, set to 2 for non-odor trials

%%
uv.evtWin = [-10 10];
if numPlanes == 1
    uv.dt = 0.1333; %can find this info in the XML - scanLinePeriod and Frame relativeTime
    uv.fs = 7.5;
    uv.pw = 35;
elseif numPlanes == 2
    uv.dt = 0.1544; %can find this info in the XML - scanLinePeriod and Frame relativeTime
    uv.fs = 6.4751;
    uv.pw = 33;
end
uv.chooseFluoresenceOrRate = 1;
uv.norm = 1; %1 for norm, 0 for no norm
uv.sigma = 0.5; %sometimes .5 sometimes .75
uv.evtSigWin.licks = [0 5];
uv.evtSigWin.stim = [0 5];
uv.evtSigWin.sucrose = [0 4];
uv.evtSigWin.quinine = [0 4]; 
uv.evtSigWin.naCl = [0 4];
uv.evtSigWin.water = [0 4];
uv.evtSigWin.none = [0 4];
uv.evtSigWin.odor = [0 5];
uv.evtSigWin.tone = [0 2];
uv.evtSigWin.pinch = [0 5];
uv.evtSigWin.puff = [0 2];
uv.evtSigWin.IRlaser = [0 5];
uv.evtSigWin.camera = [0 15];
% uv.evtSigWin.frames = [0 10];
uv.resamples = 1000;
%%
for m = 1:length(mouseData)
    if isempty(mouseData(m).name)
        continue %skip empty lines generated by skipping folders in pythonToMatlabConversion
    else
    %     fname = fieldnames(behav);
    %     behavName = fname(i);
    %     behav2 = behav.(behavName{1,1});
        for c = 1:length(mouseData(m).ca)
            ca(c,:) = mouseData(m).ca(c).trace;
        end
        behav = mouseData(m).behav;
        caTime = mouseData(m).ca(1).time;
        evtTime = uv.evtWin(1,1):uv.dt:uv.evtWin(1,2);
        evts = fieldnames(behav); 
    %     evts = string(evts);
    
        %% reformat olfactometer data if applicable
        if odor > 0
            odorTrials = load(horzcat(curFolder,'\odorTrials.csv'));
            sucroseOdor = [];
            sucroseNoOdor = [];
            for b = 1:length(behav.odor.startTS)
                if odorTrials(b) == 1
                    sucroseOdor = horzcat(sucroseOdor,b);
                elseif odorTrials(b) == 0
                    sucroseNoOdor = horzcat(sucroseNoOdor,b);
                end
            end
            if odor == 1
                trialsToAnalyze = sucroseOdor;
            elseif odor == 2
                trialsToAnalyze = sucroseNoOdor;
            end
            behav.sucrose.startTS = behav.odor.startTS+2.5; %sucrose delivery 2.5 s after odor start, workaround for missing sucrose trials
        end
    
        %% calculate time windows for each event
        evtWinSpan = max(uv.evtWin) - min(uv.evtWin);
        numMeasurements = round(evtWinSpan/uv.dt); %need to round due to odd frame rate
    %     for e = licks:length(evts) %for each event
    %         evtWinIdx.(evts{e}) = evtTime >= uv.evtSigWin.(evts{e})(1,1) &...          %calculate logical index for each event period
    %             evtTime <= uv.evtSigWin.(evts{e})(1,2);
    %     end
        %%
        fprintf('Processing data for subject %d of %d...\n', m, length(mouseData))
        tic
        for u = 1:size(ca,1)
            unitTrace = ca(u,:);
            evts(strcmp(evts,'licks'),:) = []; %exclude response to licks
            evts(strcmp(evts,'camera'),:) = []; %exclude response to camera
            for e = 1:length(evts)
%                 evts = string(evts);
                eTS = behav.(evts{e}).startTS(trialsToAnalyze);
                %% calculate logical index for each event period
                evtWinIdx.(evts{e}) = evtTime >= uv.evtSigWin.(evts{e})(1,1) &...          
                evtTime <= uv.evtSigWin.(evts{e})(1,2);
                %% initialize trial matrices
                caTraceTrials = NaN(size(eTS,1),numMeasurements);
                for t = 1:size(eTS,1)
                    %% set each trial's temporal boundaries
                    timeWin = [eTS(t)+uv.evtWin(1,1):uv.dt:eTS(t)+uv.evtWin(1,2)]; %calculate time window around each event
                    if min(timeWin) >= min(caTime) && max(timeWin) <= max(caTime) %if the beginning and end of the time window around the event occurred during the recording period. if not, the time window is out of range
                        %% get unit event counts in trials
                        %% get unit ca traces in trials
                        idx = caTime >= min(timeWin) & caTime <= max(timeWin) +uv.dt; %logical index of time window around each behavioral event time
%                         caTraceTrials(t,1:sum(idx)) = unitTrace(idx); %store the evoked calcium trace around each event   (see below, comment out if dont want normalized to whole trace)
                        if uv.norm == 0
                            caTraceTrials(t,1:sum(idx)) = unitTrace(idx);
                        else %normalize to pre-window
                            caTraceTrials(t,1:sum(idx)) = unitTrace(idx);
                            traceMean = nanmean(caTraceTrials(t,1:uv.pw)); %1:35 for 1 plane, 1:33 for 2 plane
                            traceSD = nanstd(caTraceTrials(t,1:uv.pw)); %1:35 for 1 plane, 1:33 for 2 plane
                            caTraceTrials(t,:) = (caTraceTrials(t,:) - traceMean) / traceSD;
                            clear traceMean traceSD
                        end
                    end
                end
                clear t timeWin idx eTS
                
%                 if length(evtTime) ~= length(caTraceTrials) %sometimes time or trace are 1 frame bigger
%                     caTraceTrials(:,end) = [];
%                 end
                
                %% shuffle and resample the data
                trialCt = size(caTraceTrials,1); %number of trials for currently analyzed event
                for g = 1:uv.resamples %for each resampling of the data
                    [~,shuffledIDX] = sort(randi...                   %generate a matrix of random integers from 1 to the number of measurements in each time window (not each number is generated/some are repeated)
                        (numMeasurements,trialCt,numMeasurements),2); %sort the data index to create a new list of indices
                    for t = 1:trialCt %for each trial
                        shuffledTrace(t,:) = caTraceTrials(t,shuffledIDX(t,:)); %shuffle the calcium trace
                    end
                    nullDistTrace(g,:) = nanmean(shuffledTrace); %calculate the NaN mean of the shuffled traces
                    %calculate the NaN mean of the shuffled event rates
                end
                clear shuffled* g t trialCt
                %% choose to classify fluoresence or event rates
                if uv.chooseFluoresenceOrRate == 1 %if user selected to classify the fluoresence
                    nullDist = nullDistTrace; %direct transfer
                    empiricalTrialWin = nanmean...
                        (caTraceTrials(:,evtWinIdx.(evts{e})),2); %NaN mean of the fluorescent response across trials, within the time window. this gets the within trial mean.
                    empiricalWinAvg = nanmean(empiricalTrialWin); %across trial mean
                elseif uv.chooseFluoresenceOrRate == 2 %if user selected to classify the event rates
                    nullDist = nullDistEvtRate; %direct transfer
                    empiricalTrialWin = nanmean...
                        (caEvtRateTrials(:,evtWinIdx.(evts{e})),2); %within trial average
                    empiricalWinAvg = nanmean(empiricalTrialWin); %across trial mean
                end
                clear empiricalTrialWin
                
                sdNull = std(nullDist(:)); %calculate the standard deviation of the null distribution
                upperSD = mean(nullDist(:)) + (uv.sigma*sdNull); %calculate upper limit of interval around the mean
                lowerSD = mean(nullDist(:)) - (uv.sigma*sdNull); %calculate lower limit of interval around the mean
                clear nullDist %removed sdNull on 1/13/2023
                
                respClass.(evts{e}).activated(u,1) = empiricalWinAvg > upperSD; %classify as activated if empirical response exceeds upper limit
                respClass.(evts{e}).inhibited(u,1) = empiricalWinAvg < lowerSD; %classify as inhibited if empirical response exceeds lower limit
                clear upperSD lowerSD  %removed empiricalWinAvg on 1/31/2023
                
                %% convert counts to rate
                unitXTrials(u).(evts{e}).caTraces = caTraceTrials;
                unitXTrials(u).(evts{e}).sdNull = sdNull;
                unitXTrials(u).(evts{e}).windowAvg = empiricalWinAvg;
                clear sdNull empiricalWinAvg
                
                %% store unit averaged data
                unitAVG.(evts{e}).caTraces(u,:) = nanmean(caTraceTrials); %store trial averaged calcium traces
                clear caEvtCtTrials caTraceTrials caEvtRateTrials idx
            end
        end
        clear ca u unitTS unitTrace

        toc
        final(m).name = mouseData(m).name;
        final(m).plane = mouseData(m).plane;
%         final.behav = behavName;
        final(m).time = evtTime;
        if uv.chooseFluoresenceOrRate == 1 %if user selected to classify the fluoresence
            final(m).nullDistTrace = nullDistTrace;
        elseif uv.chooseFluoresenceOrRate == 2 %if user selected to classify the event rates
            final(m).nullDistEvtRate = nullDistEvtRate;
        end
        final(m).respClass = respClass;
        final(m).unitAVG = unitAVG;
        final(m).unitXTrials = unitXTrials;
        final(m).uv = uv;
        clear evtWinIdx nullDistEvtRate nullDistTrace respClass unitAVG unitXTrials unitAverage ca u
    
        evt = fieldnames(final(m).unitAVG);
        if length(evt) == 2
            evt = flipud(fieldnames(final(1).unitAVG)); %list in reverse alphabetical order to get sucrose as evt1 and quinine as evt2
        end
        for n = 1:length(evt)
            if size(final(m).unitAVG.(evt{n}).caTraces,1)>length(mouseData(m).ca)
                final(m).unitAVG.(evt{n}).caTraces([length(mouseData(m).ca)+1:size(final(m).unitAVG.(evt{n}).caTraces,1)],:) = [];
            end

            if length(final(m).unitXTrials)>length(mouseData(m).ca)
                final(m).unitXTrials([length(mouseData(m).ca)+1:length(final(m).unitXTrials)]) = [];
            end
        end
        
    end
end

%% Track cell response before and after event of interest

for t = 1:length(evt)
    evtResponse.(evt{t}).activated = [];
    evtResponse.(evt{t}).inhibited = [];
end

for f = 1:length(final)
    for n = 1:length(evt)
        evtResponse.(evt{n}).activated = vertcat(evtResponse.(evt{n}).activated,final(f).respClass.(evt{n}).activated);
        evtResponse.(evt{n}).inhibited = vertcat(evtResponse.(evt{n}).inhibited,final(f).respClass.(evt{n}).inhibited);
    end    
end

evtResponses = [];
for s = 1:length(evt)
    evtResponses(:,4*s-3) = evtResponse.(evt{s}).activated;
    evtResponses(:,4*s-2) = evtResponse.(evt{s}).inhibited;
end
% writematrix(evtResponses,'evtResponses.csv');

clearvars -except mouseData final evt evts evtTime curFolder